on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      - uses: aviate-labs/setup-dfx@v0.3.2
        with:
          dfx-version: 0.24.3
          install-moc: true
          pocket-ic-version: 4.0.0
      - run: make test
